-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Olist e-commerce sales analysis - SQL pipeline (Databricks SQL)
-- MAGIC **Status: executed on Databricks** (serverless SQL warehouse, 2026-10-01): every statement succeeded and all 21 table row counts match the DuckDB run (see `databricks/run_outputs/`). Generated by `scripts/build_databricks.py` from `sql/`; line comments are stripped here - the fully commented SQL is in `sql/`.
-- MAGIC
-- MAGIC 1. Upload the 8 raw CSVs to the Unity Catalog volume `/Volumes/workspace/da_learn_01/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
-- MAGIC 3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_01;
USE CATALOG workspace;
USE SCHEMA da_learn_01;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`), casting happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_orders AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_orders_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_order_items AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_order_items_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_payments AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_order_payments_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_reviews AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_order_reviews_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_customers AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_customers_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_products AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_products_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_sellers AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/olist_sellers_dataset.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_category_translation AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_01/raw/product_category_name_translation.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; runs on DuckDB via 00_duckdb_compat.sql shims)

CREATE OR REPLACE TABLE cln_customers AS
WITH typed AS (
  SELECT
    lower(trim(customer_id))                                   AS customer_id,
    lower(trim(customer_unique_id))                            AS customer_unique_id,
    lpad(trim(customer_zip_code_prefix), 5, '0')               AS customer_zip_prefix,   -- restore leading zeros
    lower(trim(translate(customer_city, 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÉÊÍÓÔÕÚÇ', 'aaaaaeeeeiiiiooooouuuucAAAAEEIOOOUC'))) AS customer_city,
    upper(trim(customer_state))                                AS customer_state
  FROM stg_customers
  WHERE customer_id IS NOT NULL AND trim(customer_id) <> ''
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY customer_unique_id) AS rn FROM typed
)
SELECT customer_id, customer_unique_id, customer_zip_prefix, customer_city, customer_state
FROM ranked WHERE rn = 1;

-- COMMAND ----------

-- ---------- sellers ----------

CREATE OR REPLACE TABLE cln_sellers AS
WITH typed AS (
  SELECT
    lower(trim(seller_id))                                     AS seller_id,
    lpad(trim(seller_zip_code_prefix), 5, '0')                 AS seller_zip_prefix,
    lower(trim(translate(seller_city, 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÉÊÍÓÔÕÚÇ', 'aaaaaeeeeiiiiooooouuuucAAAAEEIOOOUC'))) AS seller_city,
    upper(trim(seller_state))                                  AS seller_state
  FROM stg_sellers
  WHERE seller_id IS NOT NULL AND trim(seller_id) <> ''
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY seller_id ORDER BY seller_zip_prefix) AS rn FROM typed
)
SELECT seller_id, seller_zip_prefix, seller_city, seller_state FROM ranked WHERE rn = 1;

-- COMMAND ----------

-- ---------- products (+ English category, fixes source typo 'lenght') ----------

CREATE OR REPLACE TABLE cln_products AS
WITH tr AS (
  SELECT lower(trim(product_category_name)) AS category_pt,
         lower(trim(product_category_name_english)) AS category_en
  FROM stg_category_translation
), typed AS (
  SELECT
    lower(trim(p.product_id))                                    AS product_id,
    NULLIF(lower(trim(p.product_category_name)), '')             AS category_pt,
    TRY_CAST(p.product_name_lenght        AS INT)                AS product_name_length,
    TRY_CAST(p.product_description_lenght AS INT)                AS product_description_length,
    TRY_CAST(p.product_photos_qty         AS INT)                AS product_photos_qty,
    TRY_CAST(p.product_weight_g           AS DOUBLE)             AS product_weight_g,
    TRY_CAST(p.product_length_cm          AS DOUBLE)             AS product_length_cm,
    TRY_CAST(p.product_height_cm          AS DOUBLE)             AS product_height_cm,
    TRY_CAST(p.product_width_cm           AS DOUBLE)             AS product_width_cm
  FROM stg_products p
  WHERE p.product_id IS NOT NULL
), ranked AS (
  SELECT t.*, ROW_NUMBER() OVER (PARTITION BY t.product_id ORDER BY t.category_pt) AS rn FROM typed t
)
SELECT
  r.product_id,
  COALESCE(r.category_pt, 'unknown')                                        AS category_pt,
  COALESCE(tr.category_en, r.category_pt, 'unknown')                        AS category_en,
  CASE WHEN r.category_pt IS NULL THEN 1 ELSE 0 END                         AS dq_missing_category,
  r.product_name_length, r.product_description_length,
  COALESCE(r.product_photos_qty, 0)                                         AS product_photos_qty,
  CASE WHEN r.product_weight_g > 0 THEN r.product_weight_g END              AS product_weight_g,  -- 0 g is not a real weight
  r.product_length_cm, r.product_height_cm, r.product_width_cm
FROM ranked r LEFT JOIN tr ON r.category_pt = tr.category_pt
WHERE r.rn = 1;

-- COMMAND ----------

-- ---------- orders (date parsing + chronology flags + RI to customers) ----------

CREATE OR REPLACE TABLE cln_orders AS
WITH typed AS (
  SELECT
    lower(trim(order_id))                                        AS order_id,
    lower(trim(customer_id))                                     AS customer_id,
    lower(trim(order_status))                                    AS order_status,
    TRY_CAST(order_purchase_timestamp      AS TIMESTAMP)         AS purchase_ts,
    TRY_CAST(order_approved_at             AS TIMESTAMP)         AS approved_ts,
    TRY_CAST(order_delivered_carrier_date  AS TIMESTAMP)         AS delivered_carrier_ts,
    TRY_CAST(order_delivered_customer_date AS TIMESTAMP)         AS delivered_customer_ts,
    TRY_CAST(order_estimated_delivery_date AS TIMESTAMP)         AS estimated_delivery_ts
  FROM stg_orders
  WHERE order_id IS NOT NULL
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY purchase_ts) AS rn FROM typed
)
SELECT
  o.order_id, o.customer_id, o.order_status,
  o.purchase_ts, o.approved_ts, o.delivered_carrier_ts, o.delivered_customer_ts, o.estimated_delivery_ts,
  CAST(o.purchase_ts AS DATE)                                                       AS purchase_date,
  CASE WHEN o.order_status = 'delivered' AND o.delivered_customer_ts IS NOT NULL THEN 1 ELSE 0 END AS is_delivered,
  ROUND((unix_timestamp(o.delivered_customer_ts) - unix_timestamp(o.purchase_ts)) / 86400.0, 2)   AS delivery_days,
  ROUND((unix_timestamp(o.estimated_delivery_ts) - unix_timestamp(o.purchase_ts)) / 86400.0, 2)   AS promised_days,
  datediff(o.delivered_customer_ts, o.estimated_delivery_ts)                                       AS days_vs_estimate, -- >0 = late
  CASE WHEN o.delivered_customer_ts IS NULL THEN NULL
       WHEN CAST(o.delivered_customer_ts AS DATE) > CAST(o.estimated_delivery_ts AS DATE) THEN 1 ELSE 0 END AS is_late,
  CASE WHEN o.delivered_customer_ts < o.purchase_ts
         OR o.approved_ts < o.purchase_ts
         OR o.delivered_carrier_ts < o.purchase_ts THEN 1 ELSE 0 END                AS dq_bad_chronology,
  CASE WHEN o.order_status = 'delivered' AND o.delivered_customer_ts IS NULL THEN 1 ELSE 0 END AS dq_delivered_without_date
FROM ranked o
WHERE o.rn = 1
  AND o.purchase_ts IS NOT NULL
  AND o.customer_id IN (SELECT customer_id FROM cln_customers);          -- referential integrity

-- COMMAND ----------

-- ---------- order items (casts, outlier flags, RI to orders/products/sellers) ----------

CREATE OR REPLACE TABLE cln_order_items AS
WITH typed AS (
  SELECT
    lower(trim(order_id))                                     AS order_id,
    TRY_CAST(order_item_id AS INT)                            AS order_item_id,
    lower(trim(product_id))                                   AS product_id,
    lower(trim(seller_id))                                    AS seller_id,
    TRY_CAST(shipping_limit_date AS TIMESTAMP)                AS shipping_limit_ts,
    TRY_CAST(price         AS DECIMAL(12,2))                  AS price,
    TRY_CAST(freight_value AS DECIMAL(12,2))                  AS freight_value
  FROM stg_order_items
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id, order_item_id ORDER BY shipping_limit_ts) AS rn FROM typed
), valid AS (
  SELECT r.* FROM ranked r
  WHERE r.rn = 1 AND r.price IS NOT NULL AND r.price > 0
    AND r.order_id   IN (SELECT order_id   FROM cln_orders)
    AND r.product_id IN (SELECT product_id FROM cln_products)
    AND r.seller_id  IN (SELECT seller_id  FROM cln_sellers)
), bounds AS (
  SELECT percentile_approx(CAST(price AS DOUBLE), 0.25) AS q1,
         percentile_approx(CAST(price AS DOUBLE), 0.75) AS q3,
         percentile_approx(CAST(price AS DOUBLE), 0.99) AS p99
  FROM valid
)
SELECT
  v.order_id, v.order_item_id, v.product_id, v.seller_id, v.shipping_limit_ts,
  v.price, COALESCE(v.freight_value, CAST(0 AS DECIMAL(12,2))) AS freight_value,
  CASE WHEN CAST(v.price AS DOUBLE) > b.q3 + 3 * (b.q3 - b.q1) THEN 1 ELSE 0 END AS is_price_outlier_iqr3,  -- extreme (3x IQR) fence
  CASE WHEN CAST(v.price AS DOUBLE) > b.p99 THEN 1 ELSE 0 END                    AS is_price_top1pct,
  CASE WHEN v.freight_value > v.price THEN 1 ELSE 0 END                          AS is_freight_gt_price
FROM valid v CROSS JOIN bounds b;

-- COMMAND ----------

-- ---------- payments ----------

CREATE OR REPLACE TABLE cln_payments AS
WITH typed AS (
  SELECT
    lower(trim(order_id))                                     AS order_id,
    TRY_CAST(payment_sequential   AS INT)                     AS payment_sequential,
    CASE WHEN lower(trim(payment_type)) IN ('not_defined', '') OR payment_type IS NULL THEN 'unknown'
         ELSE lower(trim(payment_type)) END                   AS payment_type,
    TRY_CAST(payment_installments AS INT)                     AS payment_installments_raw,
    TRY_CAST(payment_value AS DECIMAL(12,2))                  AS payment_value
  FROM stg_payments
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id, payment_sequential ORDER BY payment_value DESC) AS rn FROM typed
)
SELECT order_id, payment_sequential, payment_type,
       CASE WHEN payment_installments_raw IS NULL OR payment_installments_raw < 1 THEN 1
            ELSE payment_installments_raw END                AS payment_installments,   -- 0 installments -> 1 (single payment)
       CASE WHEN payment_installments_raw IS NULL OR payment_installments_raw < 1 THEN 1 ELSE 0 END AS dq_installments_fixed,
       payment_value,
       CASE WHEN payment_value <= 0 THEN 1 ELSE 0 END        AS dq_zero_value
FROM ranked
WHERE rn = 1 AND payment_value IS NOT NULL
  AND order_id IN (SELECT order_id FROM cln_orders);

-- COMMAND ----------

-- ---------- reviews (one review per order: latest answer wins) ----------

CREATE OR REPLACE TABLE cln_reviews AS
WITH typed AS (
  SELECT
    lower(trim(review_id))                                     AS review_id,
    lower(trim(order_id))                                      AS order_id,
    TRY_CAST(review_score AS INT)                              AS review_score,
    NULLIF(trim(review_comment_title), '')                     AS comment_title,
    NULLIF(trim(review_comment_message), '')                   AS comment_message,
    TRY_CAST(review_creation_date    AS TIMESTAMP)             AS review_created_ts,
    TRY_CAST(review_answer_timestamp AS TIMESTAMP)             AS review_answered_ts
  FROM stg_reviews
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY review_answered_ts DESC, review_id) AS rn
  FROM typed
  WHERE review_score BETWEEN 1 AND 5
)
SELECT review_id, order_id, review_score,
       CASE WHEN comment_message IS NOT NULL OR comment_title IS NOT NULL THEN 1 ELSE 0 END AS has_comment,
       COALESCE(length(comment_message), 0)                    AS comment_length,
       review_created_ts, review_answered_ts
FROM ranked
WHERE rn = 1 AND order_id IN (SELECT order_id FROM cln_orders);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema (Spark SQL dialect)

CREATE OR REPLACE TABLE dim_date AS
WITH d AS (SELECT * FROM (VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9)) AS t(n)),
nums AS (SELECT a.n + 10 * b.n + 100 * c.n + 1000 * e.n AS n FROM d a CROSS JOIN d b CROSS JOIN d c CROSS JOIN d e),
bounds AS (SELECT MIN(purchase_date) AS d0, MAX(purchase_date) AS d1 FROM cln_orders),
cal AS (SELECT date_add(b.d0, nums.n) AS date_day FROM nums CROSS JOIN bounds b WHERE nums.n <= datediff(b.d1, b.d0))
SELECT
  CAST(year(date_day) * 10000 + month(date_day) * 100 + day(date_day) AS INT) AS date_key,
  date_day                                                   AS calendar_date,
  year(date_day)                                             AS year,
  month(date_day)                                            AS month,
  CAST(date_trunc('MONTH', date_day) AS DATE)                AS month_start,
  dayofweek(date_day)                                        AS day_of_week       -- 1 = Sunday (Spark convention)
FROM cal;

-- COMMAND ----------

-- ---------- dim_customer (order-level customer_id -> person-level customer_unique_id + region + cohort) ----------

CREATE OR REPLACE TABLE dim_customer AS
WITH first_order AS (
  SELECT c.customer_unique_id, MIN(o.purchase_ts) AS first_purchase_ts
  FROM cln_orders o JOIN cln_customers c ON o.customer_id = c.customer_id
  GROUP BY c.customer_unique_id
)
SELECT
  c.customer_id, c.customer_unique_id, c.customer_zip_prefix, c.customer_city, c.customer_state,
  CASE WHEN c.customer_state IN ('SP','RJ','MG','ES') THEN 'Southeast'
       WHEN c.customer_state IN ('PR','SC','RS') THEN 'South'
       WHEN c.customer_state IN ('MT','MS','GO','DF') THEN 'Center-West'
       WHEN c.customer_state IN ('BA','SE','AL','PE','PB','RN','CE','PI','MA') THEN 'Northeast'
       WHEN c.customer_state IN ('AM','RR','AP','PA','TO','RO','AC') THEN 'North'
       ELSE 'Unknown' END                                    AS customer_region,
  CAST(date_trunc('MONTH', f.first_purchase_ts) AS DATE)     AS cohort_month
FROM cln_customers c
LEFT JOIN first_order f ON c.customer_unique_id = f.customer_unique_id;

-- COMMAND ----------

-- ---------- dim_product ----------

CREATE OR REPLACE TABLE dim_product AS
SELECT product_id, category_pt, category_en, dq_missing_category,
       product_photos_qty, product_weight_g,
       ROUND(product_length_cm * product_height_cm * product_width_cm / 1000.0, 2) AS product_volume_l
FROM cln_products;

-- COMMAND ----------

-- ---------- dim_seller ----------

CREATE OR REPLACE TABLE dim_seller AS
SELECT seller_id, seller_zip_prefix, seller_city, seller_state,
  CASE WHEN seller_state IN ('SP','RJ','MG','ES') THEN 'Southeast'
       WHEN seller_state IN ('PR','SC','RS') THEN 'South'
       WHEN seller_state IN ('MT','MS','GO','DF') THEN 'Center-West'
       WHEN seller_state IN ('BA','SE','AL','PE','PB','RN','CE','PI','MA') THEN 'Northeast'
       WHEN seller_state IN ('AM','RR','AP','PA','TO','RO','AC') THEN 'North'
       ELSE 'Unknown' END AS seller_region
FROM cln_sellers;

-- COMMAND ----------

-- ---------- fact_order_items (grain: one order line) ----------

CREATE OR REPLACE TABLE fact_order_items AS
SELECT
  i.order_id, i.order_item_id, i.product_id, i.seller_id, o.customer_id,
  CAST(year(o.purchase_date) * 10000 + month(o.purchase_date) * 100 + day(o.purchase_date) AS INT) AS order_date_key,
  o.order_status,
  CASE WHEN o.order_status IN ('canceled', 'unavailable') THEN 0 ELSE 1 END AS is_revenue_order,
  i.price, i.freight_value,
  CAST(i.price + i.freight_value AS DECIMAL(12,2)) AS item_total,
  i.is_price_outlier_iqr3, i.is_price_top1pct, i.is_freight_gt_price
FROM cln_order_items i
JOIN cln_orders o ON i.order_id = o.order_id;

-- COMMAND ----------

-- ---------- fact_orders (grain: one order) ----------

CREATE OR REPLACE TABLE fact_orders AS
WITH items AS (
  SELECT order_id, COUNT(*) AS items_qty, COUNT(DISTINCT seller_id) AS sellers_qty,
         SUM(price) AS items_value, SUM(freight_value) AS freight_value
  FROM cln_order_items GROUP BY order_id
), pay AS (
  SELECT order_id, SUM(payment_value) AS payment_value, MAX(payment_installments) AS max_installments,
         COUNT(*) AS payment_rows
  FROM cln_payments GROUP BY order_id
), main_pay AS (
  SELECT order_id, payment_type AS main_payment_type FROM (
    SELECT order_id, payment_type,
           ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY payment_value DESC, payment_sequential) AS rn
    FROM cln_payments) t
  WHERE rn = 1
)
SELECT
  o.order_id, o.customer_id, c.customer_unique_id,
  CAST(year(o.purchase_date) * 10000 + month(o.purchase_date) * 100 + day(o.purchase_date) AS INT) AS order_date_key,
  o.purchase_ts, o.order_status,
  CASE WHEN o.order_status IN ('canceled', 'unavailable') THEN 0 ELSE 1 END AS is_revenue_order,
  COALESCE(i.items_qty, 0) AS items_qty, COALESCE(i.sellers_qty, 0) AS sellers_qty,
  COALESCE(i.items_value, 0) AS items_value, COALESCE(i.freight_value, 0) AS freight_value,
  COALESCE(i.items_value, 0) + COALESCE(i.freight_value, 0) AS order_value,
  p.payment_value, mp.main_payment_type, p.max_installments,
  o.is_delivered, o.delivery_days, o.promised_days, o.days_vs_estimate, o.is_late,
  o.dq_bad_chronology,
  r.review_score, r.has_comment,
  CASE WHEN c.cohort_month = CAST(date_trunc('MONTH', o.purchase_ts) AS DATE) THEN 1 ELSE 0 END AS is_first_month_order
FROM cln_orders o
LEFT JOIN items i        ON o.order_id = i.order_id
LEFT JOIN pay p          ON o.order_id = p.order_id
LEFT JOIN main_pay mp    ON o.order_id = mp.order_id
LEFT JOIN cln_reviews r  ON o.order_id = r.order_id
LEFT JOIN dim_customer c ON o.customer_id = c.customer_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPI queries (Spark SQL dialect). Each result is materialised as a_* table

CREATE OR REPLACE TABLE a_kpi_headline AS
WITH rev AS (SELECT * FROM fact_orders WHERE is_revenue_order = 1 AND items_qty > 0),
cust AS (SELECT customer_unique_id, COUNT(*) AS n_orders FROM rev GROUP BY customer_unique_id)
SELECT
  (SELECT COUNT(*) FROM fact_orders)                                         AS orders_total,
  (SELECT COUNT(*) FROM rev)                                                 AS revenue_orders,
  (SELECT SUM(is_delivered) FROM fact_orders)                                AS delivered_orders,
  (SELECT ROUND(SUM(order_value), 2) FROM rev)                               AS gmv_brl,
  (SELECT ROUND(SUM(items_value), 2) FROM rev)                               AS product_revenue_brl,
  (SELECT ROUND(SUM(freight_value), 2) FROM rev)                             AS freight_revenue_brl,
  (SELECT ROUND(AVG(order_value), 2) FROM rev)                               AS aov_brl,
  (SELECT ROUND(AVG(items_qty), 3) FROM rev)                                 AS items_per_order,
  (SELECT COUNT(*) FROM cust)                                                AS unique_customers,
  (SELECT ROUND(100.0 * SUM(CASE WHEN n_orders > 1 THEN 1 ELSE 0 END) / COUNT(*), 2) FROM cust) AS repeat_customer_pct,
  (SELECT ROUND(AVG(review_score), 3) FROM fact_orders WHERE review_score IS NOT NULL)            AS avg_review_score,
  (SELECT ROUND(100.0 * SUM(CASE WHEN review_score <= 2 THEN 1 ELSE 0 END) / COUNT(review_score), 2) FROM fact_orders) AS low_review_pct,
  (SELECT ROUND(AVG(delivery_days), 2) FROM fact_orders WHERE is_delivered = 1 AND dq_bad_chronology = 0) AS avg_delivery_days,
  (SELECT ROUND(percentile_approx(delivery_days, 0.5), 2) FROM fact_orders WHERE is_delivered = 1 AND dq_bad_chronology = 0) AS median_delivery_days,
  (SELECT ROUND(100.0 * SUM(is_late) / COUNT(is_late), 2) FROM fact_orders WHERE is_delivered = 1) AS late_delivery_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN order_status = 'canceled' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM fact_orders) AS cancel_pct;

-- COMMAND ----------

-- Q2 Monthly revenue trend, AOV, MoM growth

CREATE OR REPLACE TABLE a_monthly_revenue AS
WITH m AS (
  SELECT d.month_start, COUNT(*) AS orders, ROUND(SUM(f.order_value), 2) AS gmv_brl,
         ROUND(AVG(f.order_value), 2) AS aov_brl, COUNT(DISTINCT f.customer_unique_id) AS customers,
         ROUND(AVG(f.review_score), 3) AS avg_review, ROUND(100.0 * SUM(f.is_late) / COUNT(f.is_late), 2) AS late_pct
  FROM fact_orders f JOIN dim_date d ON f.order_date_key = d.date_key
  WHERE f.is_revenue_order = 1 AND f.items_qty > 0
    AND d.month_start BETWEEN DATE '2017-01-01' AND DATE '2018-08-01'
  GROUP BY d.month_start
)
SELECT m.*,
       ROUND(100.0 * (gmv_brl - LAG(gmv_brl) OVER (ORDER BY month_start)) / LAG(gmv_brl) OVER (ORDER BY month_start), 2) AS gmv_mom_pct
FROM m;

-- COMMAND ----------

-- Q3 Delivery time vs review score

CREATE OR REPLACE TABLE a_delivery_vs_review AS
SELECT
  CASE WHEN delivery_days < 3 THEN '01: <3 d' WHEN delivery_days < 7 THEN '02: 3-7 d'
       WHEN delivery_days < 14 THEN '03: 7-14 d' WHEN delivery_days < 21 THEN '04: 14-21 d'
       WHEN delivery_days < 30 THEN '05: 21-30 d' ELSE '06: 30+ d' END AS delivery_bucket,
  COUNT(*) AS orders,
  ROUND(AVG(review_score), 3) AS avg_review,
  ROUND(100.0 * SUM(CASE WHEN review_score <= 2 THEN 1 ELSE 0 END) / COUNT(*), 2) AS low_review_pct,
  ROUND(100.0 * SUM(is_late) / COUNT(*), 2) AS late_pct
FROM fact_orders
WHERE is_delivered = 1 AND dq_bad_chronology = 0 AND review_score IS NOT NULL
GROUP BY 1;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_late_vs_ontime AS
SELECT CASE WHEN is_late = 1 THEN 'late' ELSE 'on_time' END AS delivery_status,
       COUNT(*) AS orders, ROUND(AVG(review_score), 3) AS avg_review,
       ROUND(100.0 * SUM(CASE WHEN review_score <= 2 THEN 1 ELSE 0 END) / COUNT(*), 2) AS low_review_pct,
       ROUND(AVG(delivery_days), 2) AS avg_delivery_days
FROM fact_orders
WHERE is_delivered = 1 AND review_score IS NOT NULL
GROUP BY 1;

-- COMMAND ----------

-- Q4 Category performance

CREATE OR REPLACE TABLE a_category_performance AS
WITH line AS (
  SELECT p.category_en, f.order_id, f.price, f.item_total
  FROM fact_order_items f JOIN dim_product p ON f.product_id = p.product_id
  WHERE f.is_revenue_order = 1
), cat AS (
  SELECT category_en, COUNT(DISTINCT order_id) AS orders, COUNT(*) AS items,
         ROUND(SUM(item_total), 2) AS gmv_brl, ROUND(AVG(price), 2) AS avg_item_price
  FROM line GROUP BY category_en
), rv AS (
  SELECT p.category_en, ROUND(AVG(o.review_score), 3) AS avg_review,
         ROUND(100.0 * SUM(o.is_late) / COUNT(o.is_late), 2) AS late_pct
  FROM (SELECT DISTINCT order_id, product_id FROM fact_order_items) x
  JOIN dim_product p ON x.product_id = p.product_id
  JOIN fact_orders o ON x.order_id = o.order_id
  GROUP BY p.category_en
)
SELECT cat.*, ROUND(100.0 * cat.gmv_brl / SUM(cat.gmv_brl) OVER (), 2) AS gmv_share_pct,
       rv.avg_review, rv.late_pct,
       RANK() OVER (ORDER BY cat.gmv_brl DESC) AS gmv_rank
FROM cat LEFT JOIN rv ON cat.category_en = rv.category_en;

-- COMMAND ----------

-- Q5 Regional (customer state) performance

CREATE OR REPLACE TABLE a_region_performance AS
SELECT c.customer_state, c.customer_region,
       COUNT(*) AS orders, COUNT(DISTINCT f.customer_unique_id) AS customers,
       ROUND(SUM(f.order_value), 2) AS gmv_brl, ROUND(AVG(f.order_value), 2) AS aov_brl,
       ROUND(100.0 * SUM(f.freight_value) / SUM(f.order_value), 2) AS freight_share_pct,
       ROUND(AVG(CASE WHEN f.is_delivered = 1 AND f.dq_bad_chronology = 0 THEN f.delivery_days END), 2) AS avg_delivery_days,
       ROUND(100.0 * SUM(f.is_late) / COUNT(f.is_late), 2) AS late_pct,
       ROUND(AVG(f.review_score), 3) AS avg_review
FROM fact_orders f JOIN dim_customer c ON f.customer_id = c.customer_id
WHERE f.is_revenue_order = 1 AND f.items_qty > 0
GROUP BY c.customer_state, c.customer_region;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_region_rollup AS
SELECT c.customer_region, COUNT(*) AS orders, ROUND(SUM(f.order_value), 2) AS gmv_brl,
       ROUND(100.0 * SUM(f.order_value) / SUM(SUM(f.order_value)) OVER (), 2) AS gmv_share_pct,
       ROUND(AVG(CASE WHEN f.is_delivered = 1 AND f.dq_bad_chronology = 0 THEN f.delivery_days END), 2) AS avg_delivery_days,
       ROUND(100.0 * SUM(f.is_late) / COUNT(f.is_late), 2) AS late_pct,
       ROUND(AVG(f.review_score), 3) AS avg_review
FROM fact_orders f JOIN dim_customer c ON f.customer_id = c.customer_id
WHERE f.is_revenue_order = 1 AND f.items_qty > 0
GROUP BY c.customer_region;

-- COMMAND ----------

-- Q6 Payment mix

CREATE OR REPLACE TABLE a_payment_mix AS
SELECT main_payment_type, COUNT(*) AS orders, ROUND(SUM(payment_value), 2) AS paid_brl,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS orders_share_pct,
       ROUND(AVG(max_installments), 2) AS avg_installments, ROUND(AVG(payment_value), 2) AS avg_payment_brl
FROM fact_orders
WHERE is_revenue_order = 1 AND main_payment_type IS NOT NULL
GROUP BY main_payment_type;

-- COMMAND ----------

-- Q7 Monthly acquisition cohorts & retention (person = customer_unique_id)

CREATE OR REPLACE TABLE a_cohort_retention AS
WITH act AS (
  SELECT DISTINCT c.customer_unique_id, c.cohort_month, CAST(date_trunc('MONTH', f.purchase_ts) AS DATE) AS active_month
  FROM fact_orders f JOIN dim_customer c ON f.customer_id = c.customer_id
  WHERE f.is_revenue_order = 1
), idx AS (
  SELECT customer_unique_id, cohort_month,
         (year(active_month) - year(cohort_month)) * 12 + (month(active_month) - month(cohort_month)) AS month_number
  FROM act
), sizes AS (SELECT cohort_month, COUNT(DISTINCT customer_unique_id) AS cohort_size FROM idx WHERE month_number = 0 GROUP BY cohort_month)
SELECT i.cohort_month, s.cohort_size, i.month_number, COUNT(DISTINCT i.customer_unique_id) AS active_customers,
       ROUND(100.0 * COUNT(DISTINCT i.customer_unique_id) / s.cohort_size, 3) AS retention_pct
FROM idx i JOIN sizes s ON i.cohort_month = s.cohort_month
WHERE i.cohort_month BETWEEN DATE '2017-01-01' AND DATE '2018-08-01'
GROUP BY i.cohort_month, s.cohort_size, i.month_number;

-- COMMAND ----------

-- Q8 Seller concentration (Pareto)

CREATE OR REPLACE TABLE a_seller_concentration AS
WITH s AS (
  SELECT seller_id, SUM(item_total) AS gmv FROM fact_order_items WHERE is_revenue_order = 1 GROUP BY seller_id
), r AS (
  SELECT seller_id, gmv, ROW_NUMBER() OVER (ORDER BY gmv DESC) AS rk, COUNT(*) OVER () AS n,
         SUM(gmv) OVER () AS total FROM s
)
SELECT CASE WHEN rk <= n * 0.01 THEN 'top_1pct' WHEN rk <= n * 0.10 THEN 'top_2_10pct'
            WHEN rk <= n * 0.50 THEN 'top_11_50pct' ELSE 'bottom_50pct' END AS seller_tier,
       COUNT(*) AS sellers, ROUND(SUM(gmv), 2) AS gmv_brl, ROUND(100.0 * SUM(gmv) / MAX(total), 2) AS gmv_share_pct
FROM r GROUP BY 1;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence (Spark SQL dialect): row counts raw vs clean,

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'orders' AS entity, (SELECT COUNT(*) FROM stg_orders) AS raw_rows, (SELECT COUNT(DISTINCT order_id) FROM stg_orders) AS distinct_keys, (SELECT COUNT(*) FROM cln_orders) AS clean_rows, 'order_id' AS grain
UNION ALL SELECT 'order_items', (SELECT COUNT(*) FROM stg_order_items), (SELECT COUNT(*) FROM (SELECT DISTINCT order_id, order_item_id FROM stg_order_items) x), (SELECT COUNT(*) FROM cln_order_items), 'order_id + order_item_id'
UNION ALL SELECT 'payments', (SELECT COUNT(*) FROM stg_payments), (SELECT COUNT(*) FROM (SELECT DISTINCT order_id, payment_sequential FROM stg_payments) x), (SELECT COUNT(*) FROM cln_payments), 'order_id + payment_sequential'
UNION ALL SELECT 'reviews', (SELECT COUNT(*) FROM stg_reviews), (SELECT COUNT(DISTINCT order_id) FROM stg_reviews), (SELECT COUNT(*) FROM cln_reviews), 'order_id (latest review kept)'
UNION ALL SELECT 'customers', (SELECT COUNT(*) FROM stg_customers), (SELECT COUNT(DISTINCT customer_id) FROM stg_customers), (SELECT COUNT(*) FROM cln_customers), 'customer_id'
UNION ALL SELECT 'products', (SELECT COUNT(*) FROM stg_products), (SELECT COUNT(DISTINCT product_id) FROM stg_products), (SELECT COUNT(*) FROM cln_products), 'product_id'
UNION ALL SELECT 'sellers', (SELECT COUNT(*) FROM stg_sellers), (SELECT COUNT(DISTINCT seller_id) FROM stg_sellers), (SELECT COUNT(*) FROM cln_sellers), 'seller_id'
UNION ALL SELECT 'fact_order_items', NULL, NULL, (SELECT COUNT(*) FROM fact_order_items), 'order line'
UNION ALL SELECT 'fact_orders', NULL, NULL, (SELECT COUNT(*) FROM fact_orders), 'order';

-- COMMAND ----------

-- raw = empty-or-NULL share in staging (strings); clean = NULL share after 02_cleaning.sql

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'orders' AS entity, 'order_approved_at' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN order_approved_at IS NULL OR trim(order_approved_at) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders) AS raw_null_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN approved_ts IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders) AS clean_null_pct,
  'kept NULL (not yet approved)' AS treatment
UNION ALL SELECT 'orders', 'order_delivered_customer_date',
  (SELECT ROUND(100.0 * SUM(CASE WHEN order_delivered_customer_date IS NULL OR trim(order_delivered_customer_date) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_orders),
  (SELECT ROUND(100.0 * SUM(CASE WHEN delivered_customer_ts IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_orders),
  'kept NULL; is_delivered = 0'
UNION ALL SELECT 'products', 'product_category_name',
  (SELECT ROUND(100.0 * SUM(CASE WHEN product_category_name IS NULL OR trim(product_category_name) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_products),
  (SELECT ROUND(100.0 * SUM(CASE WHEN category_en IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_products),
  'filled with unknown + dq_missing_category flag'
UNION ALL SELECT 'products', 'product_weight_g',
  (SELECT ROUND(100.0 * SUM(CASE WHEN product_weight_g IS NULL OR trim(product_weight_g) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_products),
  (SELECT ROUND(100.0 * SUM(CASE WHEN product_weight_g IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_products),
  '0 g set to NULL; NULL kept'
UNION ALL SELECT 'reviews', 'review_comment_message',
  (SELECT ROUND(100.0 * SUM(CASE WHEN review_comment_message IS NULL OR trim(review_comment_message) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_reviews),
  (SELECT ROUND(100.0 * SUM(CASE WHEN has_comment = 0 THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_reviews),
  'text dropped; has_comment (title or message) + comment_length kept'
UNION ALL SELECT 'payments', 'payment_type = not_defined',
  (SELECT ROUND(100.0 * SUM(CASE WHEN payment_type = 'not_defined' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_payments),
  (SELECT ROUND(100.0 * SUM(CASE WHEN payment_type = 'not_defined' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_payments),
  'recoded to unknown';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'reviews: orders with >1 review (older ones dropped)' AS check_name,
       (SELECT COUNT(*) FROM stg_reviews) - (SELECT COUNT(DISTINCT order_id) FROM stg_reviews) AS affected_rows
UNION ALL SELECT 'reviews: review_id reused across orders', (SELECT COUNT(*) FROM stg_reviews) - (SELECT COUNT(DISTINCT review_id) FROM stg_reviews)
UNION ALL SELECT 'customers: city text changed by trim/lower/accent standardization', (SELECT COUNT(*) FROM stg_customers s JOIN cln_customers c ON lower(trim(s.customer_id)) = c.customer_id WHERE s.customer_city <> c.customer_city)
UNION ALL SELECT 'customers: distinct city spellings raw', (SELECT COUNT(DISTINCT customer_city) FROM stg_customers)
UNION ALL SELECT 'customers: distinct city spellings clean', (SELECT COUNT(DISTINCT customer_city) FROM cln_customers)
UNION ALL SELECT 'sellers: distinct city spellings raw', (SELECT COUNT(DISTINCT seller_city) FROM stg_sellers)
UNION ALL SELECT 'sellers: distinct city spellings clean', (SELECT COUNT(DISTINCT seller_city) FROM cln_sellers)
UNION ALL SELECT 'products: missing category -> unknown', (SELECT SUM(dq_missing_category) FROM cln_products)
UNION ALL SELECT 'products: category without English translation', (SELECT COUNT(*) FROM cln_products p WHERE p.category_pt <> 'unknown' AND p.category_pt NOT IN (SELECT lower(trim(product_category_name)) FROM stg_category_translation))
UNION ALL SELECT 'products: weight 0 g -> NULL', (SELECT COUNT(*) FROM stg_products WHERE TRY_CAST(product_weight_g AS DOUBLE) = 0)
UNION ALL SELECT 'payments: not_defined type -> unknown', (SELECT COUNT(*) FROM cln_payments WHERE payment_type = 'unknown')
UNION ALL SELECT 'payments: 0 installments -> 1', (SELECT SUM(dq_installments_fixed) FROM cln_payments)
UNION ALL SELECT 'payments: zero-value rows (vouchers)', (SELECT SUM(dq_zero_value) FROM cln_payments)
UNION ALL SELECT 'orders: delivered status but no delivery date', (SELECT SUM(dq_delivered_without_date) FROM cln_orders)
UNION ALL SELECT 'orders: timestamps before purchase (excluded from delivery KPIs)', (SELECT SUM(dq_bad_chronology) FROM cln_orders)
UNION ALL SELECT 'orders: no order items (revenue = 0)', (SELECT COUNT(*) FROM fact_orders WHERE items_qty = 0)
UNION ALL SELECT 'orders: no payment rows', (SELECT COUNT(*) FROM fact_orders WHERE payment_value IS NULL)
UNION ALL SELECT 'orders: |payment - (price+freight)| > 1 BRL', (SELECT COUNT(*) FROM fact_orders WHERE abs(payment_value - order_value) > 1)
UNION ALL SELECT 'items: price outlier (> Q3 + 3*IQR)', (SELECT SUM(is_price_outlier_iqr3) FROM cln_order_items)
UNION ALL SELECT 'items: price in top 1%', (SELECT SUM(is_price_top1pct) FROM cln_order_items)
UNION ALL SELECT 'items: freight > price', (SELECT SUM(is_freight_gt_price) FROM cln_order_items)
UNION ALL SELECT 'RI: items with unknown order', (SELECT COUNT(*) FROM stg_order_items WHERE lower(trim(order_id)) NOT IN (SELECT order_id FROM cln_orders))
UNION ALL SELECT 'RI: items with unknown product', (SELECT COUNT(*) FROM stg_order_items WHERE lower(trim(product_id)) NOT IN (SELECT product_id FROM cln_products))
UNION ALL SELECT 'RI: items with unknown seller', (SELECT COUNT(*) FROM stg_order_items WHERE lower(trim(seller_id)) NOT IN (SELECT seller_id FROM cln_sellers))
UNION ALL SELECT 'RI: orders with unknown customer', (SELECT COUNT(*) FROM stg_orders WHERE lower(trim(customer_id)) NOT IN (SELECT customer_id FROM cln_customers))
UNION ALL SELECT 'RI: payments with unknown order', (SELECT COUNT(*) FROM stg_payments WHERE lower(trim(order_id)) NOT IN (SELECT order_id FROM cln_orders))
UNION ALL SELECT 'RI: reviews with unknown order', (SELECT COUNT(*) FROM stg_reviews WHERE lower(trim(order_id)) NOT IN (SELECT order_id FROM cln_orders));

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_orders.order_id unique' AS check_name, (SELECT COUNT(*) - COUNT(DISTINCT order_id) FROM fact_orders) AS failed_rows
  UNION ALL SELECT 'fact_order_items (order_id, order_item_id) unique', (SELECT COUNT(*) FROM (SELECT order_id, order_item_id FROM fact_order_items GROUP BY order_id, order_item_id HAVING COUNT(*) > 1) x)
  UNION ALL SELECT 'fact_order_items.product_id -> dim_product', (SELECT COUNT(*) FROM fact_order_items WHERE product_id NOT IN (SELECT product_id FROM dim_product))
  UNION ALL SELECT 'fact_order_items.seller_id -> dim_seller', (SELECT COUNT(*) FROM fact_order_items WHERE seller_id NOT IN (SELECT seller_id FROM dim_seller))
  UNION ALL SELECT 'fact_orders.customer_id -> dim_customer', (SELECT COUNT(*) FROM fact_orders WHERE customer_id NOT IN (SELECT customer_id FROM dim_customer))
  UNION ALL SELECT 'fact_orders.order_date_key -> dim_date', (SELECT COUNT(*) FROM fact_orders WHERE order_date_key NOT IN (SELECT date_key FROM dim_date))
  UNION ALL SELECT 'review_score in 1..5', (SELECT COUNT(*) FROM fact_orders WHERE review_score IS NOT NULL AND review_score NOT BETWEEN 1 AND 5)
  UNION ALL SELECT 'price > 0', (SELECT COUNT(*) FROM fact_order_items WHERE price <= 0)
  UNION ALL SELECT 'no NULL purchase_ts', (SELECT COUNT(*) FROM fact_orders WHERE purchase_ts IS NULL)
  UNION ALL SELECT 'categories trimmed/lowercase', (SELECT COUNT(*) FROM dim_product WHERE category_en <> lower(trim(category_en)))
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC Run each cell, click **+ > Visualization** under the result and configure as described in the cell comment (notebook visual settings are stored in the workspace, not in this source file). The same views are pre-built in `olist_sales_dashboard.lvdash.json`.

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Monthly GMV & AOV
-- Line chart: X = month_start, Y = gmv_brl (bar) + aov_brl (line, right axis)
SELECT month_start, orders, gmv_brl, aov_brl, gmv_mom_pct FROM a_monthly_revenue ORDER BY month_start;

-- COMMAND ----------

-- Visualization: Delivery time vs review
-- Bar chart: X = delivery_bucket, Y = avg_review; secondary = low_review_pct
SELECT delivery_bucket, orders, avg_review, low_review_pct FROM a_delivery_vs_review ORDER BY delivery_bucket;

-- COMMAND ----------

-- Visualization: Top 10 categories
-- Horizontal bar: Y = category_en, X = gmv_brl; tooltip avg_review
SELECT category_en, gmv_brl, orders, avg_review, late_pct FROM a_category_performance WHERE gmv_rank <= 10 ORDER BY gmv_rank;

-- COMMAND ----------

-- Visualization: States
-- Bar: X = customer_state, Y = gmv_brl; line: avg_delivery_days
SELECT customer_state, customer_region, gmv_brl, aov_brl, avg_delivery_days, late_pct, avg_review FROM a_region_performance ORDER BY gmv_brl DESC;

-- COMMAND ----------

-- Visualization: Cohort retention
-- Heatmap (Pivot table visual): rows = cohort_month, columns = month_number, values = retention_pct
SELECT cohort_month, month_number, retention_pct FROM a_cohort_retention WHERE month_number BETWEEN 1 AND 6 ORDER BY 1, 2;

-- COMMAND ----------

-- Visualization: Payment mix
-- Pie: angle = orders, color = main_payment_type
SELECT main_payment_type, orders, orders_share_pct, avg_installments FROM a_payment_mix ORDER BY orders DESC;
