#!/usr/bin/env python3
"""Generate databricks/olist_pipeline_notebook.sql (Databricks SQL notebook source) from sql/02-05 and
databricks/olist_sales_dashboard.lvdash.json (AI/BI Lakeview dashboard) so both stay in sync with the
DuckDB-tested SQL. Only the staging cells differ (read_files instead of DuckDB read_csv); 00_duckdb_compat.sql is skipped.
Usage: python scripts/build_databricks.py [--with-dashboard]   (dashboard JSON is only rewritten with the flag)"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG, SCHEMA, VOLUME = "workspace", "da_learn_01", "/Volumes/workspace/da_learn_01/raw"
FILES = {"stg_orders": "olist_orders_dataset.csv", "stg_order_items": "olist_order_items_dataset.csv",
         "stg_payments": "olist_order_payments_dataset.csv", "stg_reviews": "olist_order_reviews_dataset.csv",
         "stg_customers": "olist_customers_dataset.csv", "stg_products": "olist_products_dataset.csv",
         "stg_sellers": "olist_sellers_dataset.csv", "stg_category_translation": "product_category_name_translation.csv"}
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    """Return SQL statements split on ";" at end of line; keeps the first comment line, drops other full-line comments."""
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line.split("--")[0] if line[:line.find("--")].count("'") % 2 == 0 else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            out.append("\n".join(([head] if head else []) + keep).strip()); buf = []
    return out


VIZ = [
    ("Monthly GMV & AOV", "Line chart: X = month_start, Y = gmv_brl (bar) + aov_brl (line, right axis)",
     "SELECT month_start, orders, gmv_brl, aov_brl, gmv_mom_pct FROM a_monthly_revenue ORDER BY month_start"),
    ("Delivery time vs review", "Bar chart: X = delivery_bucket, Y = avg_review; secondary = low_review_pct",
     "SELECT delivery_bucket, orders, avg_review, low_review_pct FROM a_delivery_vs_review ORDER BY delivery_bucket"),
    ("Top 10 categories", "Horizontal bar: Y = category_en, X = gmv_brl; tooltip avg_review",
     "SELECT category_en, gmv_brl, orders, avg_review, late_pct FROM a_category_performance WHERE gmv_rank <= 10 ORDER BY gmv_rank"),
    ("States", "Bar: X = customer_state, Y = gmv_brl; line: avg_delivery_days",
     "SELECT customer_state, customer_region, gmv_brl, aov_brl, avg_delivery_days, late_pct, avg_review FROM a_region_performance ORDER BY gmv_brl DESC"),
    ("Cohort retention", "Heatmap (Pivot table visual): rows = cohort_month, columns = month_number, values = retention_pct",
     "SELECT cohort_month, month_number, retention_pct FROM a_cohort_retention WHERE month_number BETWEEN 1 AND 6 ORDER BY 1, 2"),
    ("Payment mix", "Pie: angle = orders, color = main_payment_type",
     "SELECT main_payment_type, orders, orders_share_pct, avg_installments FROM a_payment_mix ORDER BY orders DESC"),
]


def notebook():
    cells = ["-- Databricks notebook source\n" + md(f"""
# Olist e-commerce sales analysis - SQL pipeline (Databricks SQL)
**Status: executed on Databricks** (serverless SQL warehouse, 2026-10-01): every statement succeeded and all 21 table row counts match the DuckDB run (see `databricks/run_outputs/`). Generated by `scripts/build_databricks.py` from `sql/`; line comments are stripped here - the fully commented SQL is in `sql/`.

1. Upload the 8 raw CSVs to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.""")]
    cells.append(f"-- Config: change catalog / schema here (and in the dashboard JSON) if needed\nCREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging - all columns as STRING (`inferColumnTypes => false`), casting happens in 02"))
    for t, f in FILES.items():
        cells.append(f"CREATE OR REPLACE TABLE {t} AS\nSELECT *\nFROM read_files('{VOLUME}/{f}',\n  format => 'csv', header => true, multiLine => true, escape => '\"', inferColumnTypes => false);")
    titles = {"02_cleaning.sql": "02 Cleaning", "03_model.sql": "03 Star schema", "04_analysis.sql": "04 Business KPIs",
              "05_quality_checks.sql": "05 Data-quality checks"}
    for f, title in titles.items():
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append(md("## Quality summary\nAll assertions should be PASS."))
    cells.append("SELECT * FROM dq_row_counts ORDER BY entity;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md("## Visualizations\nRun each cell, click **+ > Visualization** under the result and configure as described in the cell comment (notebook visual settings are stored in the workspace, not in this source file). The same views are pre-built in `olist_sales_dashboard.lvdash.json`."))
    cells.append("SELECT * FROM a_kpi_headline;")
    for title, how, q in VIZ:
        cells.append(f"-- Visualization: {title}\n-- {how}\n{q};")
    return SEP.join(cells) + "\n"


def ds(name, display, sql):
    return {"name": name, "displayName": display, "queryLines": [sql]}


def field(n, expr=None):
    return {"name": n, "expression": expr or f"`{n}`"}


def widget(name, ds_name, fields, spec, pos):
    return {"widget": {"name": name, "queries": [{"name": "main_query", "query": {"datasetName": ds_name, "fields": fields, "disaggregated": True}}], "spec": spec}, "position": pos}


def counter(name, col, title, fmt, x, y=1):
    enc = {"fieldName": col, "displayName": title}
    if fmt: enc["format"] = fmt
    return widget(name, "kpi", [field(col)], {"version": 2, "widgetType": "counter", "encodings": {"value": enc}, "frame": {"showTitle": True, "title": title}}, {"x": x, "y": y, "width": 1, "height": 2})


def chart(name, kind, ds_name, x, y, title, pos, xs="categorical", ys="quantitative", horizontal=False):
    xe = {"fieldName": x[0], "displayName": x[1], "scale": {"type": xs}}
    ye = {"fieldName": y[0], "displayName": y[1], "scale": {"type": ys}}
    enc = {"x": ye, "y": xe} if horizontal else {"x": xe, "y": ye}
    return widget(name, ds_name, [field(x[0]), field(y[0])], {"version": 3, "widgetType": kind, "encodings": enc, "frame": {"showTitle": True, "title": title}}, pos)


def dashboard():
    q = lambda t: f"{CATALOG}.{SCHEMA}.{t}"
    brl = {"type": "number-currency", "currencyCode": "BRL", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 2}}
    pct = {"type": "number-percent", "decimalPlaces": {"type": "max", "places": 2}}
    datasets = [
        ds("kpi", "Headline KPIs", f"SELECT gmv_brl, revenue_orders, aov_brl, unique_customers, repeat_customer_pct / 100 AS repeat_rate, avg_review_score, late_delivery_pct / 100 AS late_rate FROM {q('a_kpi_headline')}"),
        ds("monthly", "Monthly revenue", f"SELECT month_start, orders, gmv_brl, aov_brl FROM {q('a_monthly_revenue')}"),
        ds("delivery", "Delivery vs review", f"SELECT delivery_bucket, orders, avg_review, low_review_pct FROM {q('a_delivery_vs_review')} ORDER BY delivery_bucket"),
        ds("category", "Top categories", f"SELECT category_en, gmv_brl, avg_review FROM {q('a_category_performance')} WHERE gmv_rank <= 10"),
        ds("state", "State performance", f"SELECT customer_state, gmv_brl, avg_delivery_days, late_pct, avg_review FROM {q('a_region_performance')} ORDER BY gmv_brl DESC"),
    ]
    # 8 visuals: 4 KPI counters + revenue trend + category bars (page 1); delivery-vs-review + state bars (page 2)
    p1 = [{"widget": {"name": "title", "multilineTextboxSpec": {"lines": ["## Olist e-commerce sales - executive overview (full data, BRL)"]}}, "position": {"x": 0, "y": 0, "width": 6, "height": 1}},
          counter("kpi_gmv", "gmv_brl", "GMV", brl, 0), counter("kpi_aov", "aov_brl", "AOV", brl, 1),
          counter("kpi_review", "avg_review_score", "Avg review (1-5)", None, 2), counter("kpi_late", "late_rate", "Late deliveries", pct, 3),
          {"widget": {"name": "kpi_note", "multilineTextboxSpec": {"lines": ["Revenue = price + freight of orders not canceled/unavailable. Trend: complete months 2017-01..2018-08. Source: Olist (Kaggle), CC BY-NC-SA 4.0."]}}, "position": {"x": 4, "y": 1, "width": 2, "height": 2}},
          chart("monthly_gmv", "line", "monthly", ("month_start", "Month"), ("gmv_brl", "GMV (BRL)"), "Monthly GMV trend", {"x": 0, "y": 3, "width": 6, "height": 6}, xs="temporal"),
          chart("top_categories", "bar", "category", ("category_en", "Category"), ("gmv_brl", "GMV (BRL)"), "Top 10 categories by GMV", {"x": 0, "y": 9, "width": 6, "height": 7}, horizontal=True)]
    p2 = [{"widget": {"name": "title2", "multilineTextboxSpec": {"lines": ["## Delivery, satisfaction & regions"]}}, "position": {"x": 0, "y": 0, "width": 6, "height": 1}},
          chart("delivery_review", "bar", "delivery", ("delivery_bucket", "Delivery time (purchase -> customer)"), ("avg_review", "Avg review"), "Delivery time vs average review score", {"x": 0, "y": 1, "width": 6, "height": 6}),
          chart("state_gmv", "bar", "state", ("customer_state", "Customer state"), ("gmv_brl", "GMV (BRL)"), "GMV by customer state", {"x": 0, "y": 7, "width": 6, "height": 6})]
    return {"datasets": datasets, "pages": [
        {"name": "overview", "displayName": "Executive overview", "pageType": "PAGE_TYPE_CANVAS", "layout": p1},
        {"name": "operations", "displayName": "Delivery & regions", "pageType": "PAGE_TYPE_CANVAS", "layout": p2}]}


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / "olist_pipeline_notebook.sql").write_text(notebook())
    if "--with-dashboard" in sys.argv:  # the committed .lvdash.json is the copy exported back from the workspace
        (out / "olist_sales_dashboard.lvdash.json").write_text(json.dumps(dashboard(), separators=(",", ":")) + "\n")
    print("wrote", sorted(p.name for p in out.iterdir()))
